name: PlatformIO CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [ "heltec_wifi_lora_32_V3" ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build regenfass
        run: pio run -e ${{ matrix.environment }}
      - uses: actions/upload-artifact@v2
        with:
          name: regenfass-${{ matrix.environment }}
          path: |
            build_output/regenfass/*.bin
            build_output/regenfass/*.gz
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: regenfass-release
          path: build_output/release/*.bin

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [get_default_envs, build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: regenfass-release
    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        draft: True
        files: |
          *.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}